site_name: Moonlight Terminal Game

repo_name:  "2025.1-Moonlighter"
repo_url: https://github.com/SBD1/2025.1-Moonlighter
site_description: "Documentação do jogo Moonlight Terminal Game"

nav:
  - Home: index.md
  - Metodologia: metodologia.md
  - Módulo 1:
    - Diagrama Entidade-Relacionamento: pages/Modulo1/Diagrama_Entidade_Relacionamento.md
    - Modelo Relacional: pages/Modulo1/modelo_relacional.md
    - Dicionário de Dados: pages/Modulo1/Dicionario.md
    - Vídeo de Apresentação: pages/Modulo1/VideoApresentacao.md
  - Módulo 2:
    - Data Definition Language: pages/Modulo2/DDL.md
    - Data Manipulation Language: pages/Modulo2/DML.md
    - Data Query Language: pages/Modulo2/DQL.md
    - Vídeo de Apresentação: pages/Modulo2/VideoApresentacao.md
  - Módulo 3:
    - Triggers: pages/Modulo3/Triggers.md
    - Stored Procedures: pages/Modulo3/StoredProcedures.md
    

theme:
  name: material
  language: pt-BR

  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.top
    - navigation.tracking
  
  palette:
    - scheme: default
      primary: 'custom'
      accent: 'lime'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mude para o tema escuro
        
    - scheme: slate
      primary: 'custom'
      accent: 'lime'
      toggle:
        icon: material/toggle-switch
        name: Mude para o tema claro

  
  logo: assets/Moonlighter_Icon.png
  favicon: assets/Moonlighter_Icon.png
  highlightjs: true

extra_css:
  - overrides/styles.css

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
