name: Nova Documentação
description: Registre uma nova atividade envolvendo Documentação no projeto Moonlighter.
title: "[DOC]: <Título BREVE da Atividade>"
body:
  - type: textarea
    id: text-zone1
    attributes:
      label: O que deve ser feito nesta seção da documentação.
      description: Descreva aqui os detalhes do que deverá ser escrito na documentação.
    validations:
      required: true
  - type: textarea
    id: text-zone3
    attributes:
      label: Detalhes adicionais?
      description: Acrescente detalhes pertinentes.
      placeholder: |
        Escreva ou deixe em branco.