name: Nova Feature
description: Registre uma nova Feature no projeto Moonlighter.
title: "[FEAT]: <Título da feature no verbo Infinitivo>"
labels: ["feature"]
body:
  - type: textarea
    id: text-zone1
    attributes:
      label: Descreva a História de Usuário
      description: siga o modelo - Quem deve operar o sistema? O que deve sistema deve fazer? Para qual objetivo o ator deve fazer isso?
      value: O || Eu como [Ator da Ação], deve ser capaz de [o que deve fazer], para que [Objetivo].
    validations:
      required: true
  - type: textarea
    id: text-zone2
    attributes:
      label: Quais são as Definition's of Ready (DoR) da atividade?
      description: O que deve ser verificado e feito pelo time para que a funcionalidade inicie sua fase de codificação?
      value: |
        - [ ] Constuir a História de Usuário no formato _"Eu como [Ator], devo ser capaz de [o que fazer], para que [objetivo]"_;
        - [ ] Os critérios de aceitação foram construídos;
        ...
    validations:
      required: true
  - type: textarea
    id: text-zone3
    attributes:
      label: Quais são as Definition's of Done (DoD) da atividade?
      description: O que deve ser testado e estar funcionando para que a User Story esteja concluída?
      value: |
        - [ ] Os critérios de aceitação foram supridos;
        - [ ] O backend foi integrado à interface (se aplicável);
        - [ ] Todo o código passou por revisão de pares para garantir qualidade e aderência aos padrões do projeto, isto é, 2 revisores aprovaram o código.
        - [ ] A funcionalidade foi integrada ao branch principal sem conflitos.
      
        ### CRITÉRIOS DE ACEITAÇÃO:
        - [ ] Critério 1;
        - [ ] Critério 2;
    validations:
      required: true
  - type: textarea
    id: text-zone4
    attributes:
      label: Detalhes adicionais?
      description: Acrescente detalhes pertinentes.
      placeholder: |
        Escreva ou deixe em branco.