-- INSERÇÕES DE TUPLAS NAS TABELAS

-- INSERÇÃO NA TABELA ITENS:
INSERT INTO "item"
    ("nome", "descricao", "tipo", "precoBase", "cultura", "stackMaximo", "idEfeito")
    VALUES
    -- ITENS SEM CATEGORIA:
    ('Espada Quebrada', 'Bastante inútil na sua forma atual, mas eu poderia ser facilmente derretido para criar algo novo!', 'Item', 150, 'Golem', 5, NULL),
    ('Tecido', 'Robusto, mas áspero ao tato. Imagino que alguns queiram utilizá-lo na criação de decorações.', 'Item', 250, 'Golem', 5, NULL),
    ('Restos de Fundição', 'Creio que isto são os restos de uma antiga fundição. Se os Golems foram criados, o que é que os criou?', 'Item', 150, 'Golem', 5, NULL),
    ('Cinzel de Golem', 'Esse é definitivamente um cinzel usado para esculpir e moldar um Golem. Por sua estrutura, imagino que os arquitetos não eram muito diferentes de nós.', 'Item', 500, 'Golem', 5, NULL),
    ('Aço Endurecido', 'O aço mais forte que já encontrei. Perfeito para a criação de novos equipamentos.', 'Item', 300, 'Golem', 5, NULL),
    ('Barra de Ferro', 'Ferro. Bastante básico, mas a pedra fundamental de qualquer equipamento de nível médio que se queira fabricar.', 'Item', 25, 'Golem', 10, NULL),
    ('Geléia Rica', 'Substância gelatinosa com muitas propriedades curativas. Pode ser extraída de vários Slimes. Essencial na preparação de poções.', 'Item', 5, 'Mercador', 10, NULL),
    ('Raíz', 'Uma raiz de uma planta gigante. Muito útil para a criação de novos arcos.', 'Item', 5, 'Golem', 10, NULL),
    ('Ferramenta Rúnica', 'Parece ter sido uma ferramenta usada para inscrever texto em metal e pedra. Talvez possa ser usada para inscrever runas em meu equipamento.', 'Item', 1500, 'Golem', 5, NULL),
    ('Pedra de Dente', 'Pedra muito afiada, comumente encontrada nos corpos de Golems antigos.', 'Item', 5, 'Golem', 10, NULL),
    ('Cipó', 'Um material forte, porém flexível, usado pelas criaturas Tangle para se protegerem.', 'Item', 2, 'Golem', 10, NULL),
    ('Esfera de Água', 'Uma esfera branca leitosa ou algum material desconhecido contendo água emitindo uma luz estranha, quase sinistra.', 'Item', 100, 'Golem', 10, NULL),
    ('Pedra de Amolar', 'Pedra básica usada por ferreiros para amolar e afiar armas. Nunca é demais ter uma pedra dessas.', 'Item', 15, 'Golem', 10, NULL),
    ('Madeira Antiga', 'Madeira petrificada devido a anos de permanência em ambientes com elementos específicos.', 'Item', 1000, 'Floresta', 5, NULL),
    ('Madeira Mágica', 'Madeira embebida em resíduos mágicos durante anos. Emite pequenas faíscas azuis. Material potencialmente útil para resistir a outras magias elementares.', 'Item', 100, 'Floresta', 10, NULL),
    ('Bulbo Antigo', 'Um bulbo bastante grande que pertenceu a uma planta já morta... Não está vivo... mas também não está realmente morto...', 'Item', 2000, 'Floresta', 5, NULL),
    ('Raíz Preservada', 'Uma raiz muito antiga e muito bem preservada.', 'Item', 600, 'Floresta', 5, NULL),
    ('Ácido Puro', 'Puro ácido. Não sei o que me levou a tentar colecionar esse material. Derrete em quase tudo.', 'Item', 400, 'Floresta', 10, NULL),
    ('Palha', 'Uma simples pilha de palha. Nada surpreendente. No entanto, parece estar coberto por alguns líquidos corrosivos. Talvez tenha sido usado como isolamento para alguma coisa?', 'Item', 500, 'Floresta', 5, NULL),
    ('Folhas Fortes', 'Folhas endurecidas que são flexíveis o suficiente para ricochetear nas paredes em vez de se estilhaçar. Essa foi uma lição duramente aprendida...', 'Item', 400, 'Floresta', 10, NULL),
    ('Geléia de Veneno', 'Uma variante de geleia venenosa encontrada em slimes da floresta. Extraia com cuidado.', 'Item', 20, 'Floresta', 10, NULL),
    ('Corda do Deserto', 'Uma corda... que não pega fogo... Quem quer que tenha residido na Masmorra do Deserto deve ter sido um povo incrivelmente inventivo.', 'Item', 450, 'Deserto', 5, NULL),
    ('Lingote De Aço do Deserto', 'Aço bruto encontrado na Masmorra do Deserto. Anos de ventos arenosos parecem tê-lo endurecido mais do que a maioria dos metais.', 'Item', 7500, 'Deserto', 5, NULL),
    ('Joia de Fogo', 'Faísca instantânea ao entrar em contato com uma pedra ou até mesmo com um pano grosso. Um iniciador de fogo perfeito.', 'Item', 1700, 'Deserto', 10, NULL),
    ('Geléia de Fogo', 'Uma variante de gelatina que parece estar sempre pegando fogo... Encontrada nos Slimes do Deserto. Não posso beber nada feito com isso... posso?', 'Item', 100, 'Mercador', 10, NULL),
    ('Tecido à Prova de Fogo', 'Um tecido que se recusa a queimar. Frequentemente encontrado enrolado em pilhas de areia. Possivelmente usado para proteger a areia durante um processo de aquecimento extremo?', 'Item', 1150, 'Deserto', 10, NULL),
    ('Pó Inflamável', 'Pó altamente inflamável. Ótimo para reacender o fogo. Preciso ter alguns em estoque perto do fogão.', 'Item', 400, 'Deserto', 10, NULL),
    ('Pó de Insolação', 'Pó usado para isolar conduítes do calor.', 'Item', 2050, 'Deserto', 10, NULL),
    ('Magnetita', 'Um mineral usado para magnetizar outros materiais.', 'Item', 800, 'Deserto', 10, NULL),
    ('Motor Termomagnético', 'Com tantas peças giratórias, ele parece mágico. Um dispositivo que transforma a energia térmica em ondas magnéticas.', 'Item', 9200, 'Deserto', 5, NULL),
    ('Metal Condutor', 'Sucata de metal encontrada em torno da Masmorra da Tecnologia. Pode ser usado como condutor durante a fabricação.', 'Item', 600, 'Tecnologia', 10, NULL),
    ('Bobina de Cobre', 'O cobre condutor é fiado em fios e depois enrolado nessa bobina. Fácil de acessar. Design criativo.', 'Item', 7500, 'Tecnologia', 5, NULL),
    ('Geléia Elétrica', 'Essa geleia é elétrica, e não estou falando de movimentos de dança... Extraído de Slimes da Tecnologia. Eu poderia criar algumas armas inéditas com isso.', 'Item', 400, 'Mercador', 10, NULL),
    ('Fios de Ouro', 'Fios de ouro reais entrelaçados em fios usados por muitas das máquinas das masmorras da Tecnologia. A manutenção deve ser cara.', 'Item', 2100, 'Tecnologia', 10, NULL),
    ('Madeira Tratada', 'Madeira tratada para resistir a líquidos corrosivos.', 'Item', 5150, 'Tenologia', 5 , NULL),
    ('Bateria de Célula Tripla', 'Uma variante muito maior do Capacitor. Aparentemente, ele pode armazenar grandes quantidades de energia não mágica.', 'Item', 10000, 'Tecnologia', 5, NULL),
    ('Pistola de Solda', 'Com o uso de vários outros recursos, esse dispositivo pode unir firmemente determinados metais.', 'Item', 11650, 'Tecnologia', 5, NULL),
    ('Fios', 'Pequenos fios de metal usados para conduzir eletricidade.', 'Item', 2550, 'Tecnologia', 10, NULL),
    ('Pedra de Wolfram', 'Uma versão bruta do metal tungstênio. Não processado, mas certamente valioso para quem precisa do material.', 'Item', 6350, 'Tecnologia', 5, NULL),
    ('Adapatador AC', 'Normalmente, eles se encontram entre uma “bateria” e o que requer energia. Deve ser algum tipo de conversor.', 'Item', 15550, 'Tenologia', 5, NULL),
    ('Pote Antigo', 'Tem uma ou duas pequenas rachaduras, mas ainda pode conter algo. Muito bem trabalhado. Curioso para saber para que poderia ter sido usado.', 'Item', 100, 'Tecnologia', 5, NULL),
    ('Frasco de Argônio', 'Com frequência, eu encontrava o gás nesse frasco perto de metal limpo e sem manchas. Ele deve evitar algum tipo de processo químico que resulte em ferrugem.', 'Item', 12050, 'Tecnologia', 5, NULL),
    ('Folhas de Lâminas', 'Folhas afiadas usadas como armas de projétil por vários inimigos bastante incômodos...', 'Item', 300, 'Floresta', 10, NULL),
    ('Anotações de Botânica I', 'Originalmente, queríamos melhorar o tamanho da colheita, mas a introdução da cepa LF1 parece ter dado às plantas uma autoconsciência...', 'Book', 2000, 'Floresta', 5, NULL),
    ('Anotações de Botânica II', 'Plantas que se movem por conta própria? As possibilidades são ilimitadas. Uma colheita melhor é apenas o começo! Será que poderíamos domesticá-las?', 'Book', 2000, 'Floresta', 5, NULL),
    ('Anotações de Botânica III', 'Com a injeção contínua da cepa LF1, determinadas plantas se tornaram criaturas formidáveis capazes de agressão. Precisamos manter isso na linha.', 'Book', 2000, 'Floresta', 5, NULL),
    ('Bateria Quebrada', 'Um receptáculo quebrado para energia não mágica... Quem criou todos esses artefatos?', 'Item', 2850, 'Tecnologia', 10, NULL),
    ('Taco Quebrado', 'O taco está quebrado e não tem conserto.', 'Item', 300, 'Mercador', 1, NULL),
    ('Arco Quebrado', 'O Arco e Flexa está quebrado e não tem conserto', 'Item', 10000, 'Mercador', 1, NULL),
    ('Adaga Quebrada', 'A Adaga está quebrada e não tem conserto', 'Item', 20000, 'Mercador', 1, NULL),
    ('Katana Quebrada', 'A Katana está quebrada e não tem conserto', 'Item', 2000, 'Mercador', 1, NULL),
    ('Maça Qubrada', 'A Maça está quebrada e não tem conserto', 'Item', 300, 'Mercador', 1, NULL),
    ('Clava Quebrada', 'A Clava está quebrada e não tem conserto', 'Item', 10000, 'Mercador', 1, NULL),
    ('Arpão Quebrado', 'Um pedaço de metal velho, torto e inútil.', 'Item', 2000, 'Mercador', 1, NULL),
    ('Estilingue Quebrado', 'Um pedaço de couro esfarrapado e cheio de buracos. Ele nunca mais disparará um projétil.', 'Item', 300, 'Mercador', 1, NULL),
    ('Chicote Quebrado', 'O couro está completamente estragado, provavelmente já foi um ótimo chicote.', 'Item', 20000, 'Mercador', 1, NULL),
    ('Observações sobre Mutae Carnívora', 'Ao introduzir um fluxo constante de LF1 em uma planta em vez de injeções, esperamos criar uma planta grande o suficiente para produzir frutos para uma cidade!', 'Item', 5000, 'Floresta', 5, NULL),
    ('Sementes de Mutae Carnívora', 'Sementes que saíram do Guardião da Floresta ao derrotá-lo. Elas devem ser únicas. Curioso... Elas poderiam se transformar em algo?...', 'Item', 5000, 'Floresta', 5, NULL),
    ('Lava Resfriada', 'Lava que parece ter sido congelada rapidamente. Sempre fria ao toque.', 'Item', 2500, 'Deserto', 5, NULL),
    ('Tintura de Tecido', 'Parece que esse corante pode ser à prova de fogo em qualquer peça de roupa em que for aplicado. A Masmorra do Deserto está repleta de itens interessantes.', 'Item', 2750, 'Deserto', 5, NULL),
    ('Rocha de Cristal', 'Um belo cristal de muitas cores. Ouvi rumores de que ele está sendo usado como condutor com resultados fantásticos.', 'Item', 75, 'Golem', 10, NULL),
    ('Fragmentos de Cristal', 'Cristais quebrados... O desgaste e as marcas indicam a possibilidade de que algum tipo de energia tenha passado por eles.', 'Item', 500, 'Tecnologia', 10, NULL),
    ('Energia Cristalizada', 'Parece que a energia que surge em um Golem se cristaliza após sua destruição. Será que podemos aproveitar esse poder de alguma forma?', 'Item', 100, 'Golem', 10, NULL),
    ('História do Deserto I', 'Três sóis perfuram o céu. Lançando luz quase infinita sobre nós. Suas rotações estão alinhadas para permitir apenas dois dias de escuridão por ano.', 'Book', 15000, 'Deserto', 5, NULL),
    ('História do Deserto II', 'As três irmãs no céu estão sempre nos vigiando. Nossos dias são longos e quentes, mas a energia das irmãs nos deu muitos presentes.', 'Book', 15000, 'Deserto', 5, NULL),
    ('História do Deserto III', 'Seu calor ilimitado nos deu o controle das chamas. Ele alimentou nossas máquinas. E criou a lava eterna que protege nossas cidades.', 'Book', 15000, 'Deserto', 5, NULL),
    ('Chapa de Aço do Deserto', 'Um metal resistente que se torna incrivelmente flexível quando uma corrente magnética passa por ele. É preciso que o ferreiro faça experimentos com isso.', 'Item', 2500, 'Deserto', 10, NULL),
    ('Pedra do Deserto', 'Pedra branca polida com alto ponto de fusão.', 'Item', 2700, 'Deserto', 5, NULL),
    ('Areia Doamantinética', 'Areia que realmente reage a campos magnéticos. É raro, mas já vi várias esculturas usarem esse material para criar cenas flutuantes de areia.', 'Item', 500, 'Deserto', 10, NULL),
    ('Cristal Capacitador', 'Fonte de cristal bruto de poder mágico.', 'Item', 100, 'Mercador', 5, NULL),
    ('Capacitor de Energia', 'Objeto pequeno. Tomo diz que ele pode armazenar energia sem magia. Isso pode ser útil para qualquer pessoa.', 'Item', 4500, 'Tecnologia', 5, NULL),
    ('Solo Fértil', 'Um solo muito rico que, se transportado corretamente, pode levar a uma planta substancialmente mais saudável do que o solo padrão.', 'Item', 1000, 'Floresta', 5, NULL),
    ('Fertilizante', 'Um fertilizante forte que pode levar a um crescimento maior do que a média das plantas.', 'Item', 1000, 'Floresta', 5, NULL),
    ('Condutor de Fluido', 'Um conduíte para o transporte de fluido, provavelmente lava. Parece projetado para minimizar qualquer perda de calor durante o transporte.', 'Item', 3650, 'Deserto', 5, NULL),
    ('Recipiente para Fluidos', 'Desenhos tão ornamentados para algo que parece tão básico. É simplesmente um recipiente destinado a misturar vários fluidos e substâncias.', 'Item', 1550, 'Floresta', 5, NULL),
    ('Observações sobre a Energia de Fluxo', 'Criada por meio de compressão de magia, esta é a maior conquista de nosso tempo - Energia de Fluxo. Para servir tanto como protetor quanto como fonte de energia.', 'Item', 40000, 'Tecnologia', 5, NULL),
    ('Frutas da Floresta', 'Várias frutas colhidas na Masmorra da Floresta... Algumas foram comprovadas como seguras para consumo. Outras... não.', 'Item', 1800, 'Floresta', 5, NULL),
    ('História da Floresta I', 'Éramos uma espécie inteligente. Portanto, quando a escassez de alimentos aumentou, acreditamos que poderíamos resolver nosso problema com a ciência...', 'Book', 5000, 'Floresta', 5, NULL),
    ('História da Floresta II', 'Criamos o LF1 e, por algum tempo, as coisas foram boas. A comida voltou a ser abundante e as florestas começaram a aparecer pela primeira vez em séculos!', 'Book', 5000, 'Floresta', 5, NULL),
    ('História da Floresta III', 'No entanto, a floresta não parou de crescer... e, aos poucos, nosso mundo foi coberto. As plantas não pararam de crescer... e lentamente... elas tomaram conta.', 'Book', 5000, 'Floresta', 5, NULL),
    ('Lentes de Vidro', 'Vidro moldado em uma lente com o único propósito de focalizar a energia mágica. Muito útil na fabricação de armas mágicas.', 'Item', 100, 'Golem', 5, NULL),
    ('Runas de Ouro', 'Essas Runas de Ouro criam padrões maravilhosos nos Golems. Ocasionalmente, você pode recuperar uma intacta após a batalha.', 'Item', 300, 'Golem', 5, NULL),
    ('Nécleo de Golem', 'O núcleo do próprio “coração” de um Golem. Encontramos maneiras de aproveitar a energia, mas não conseguimos criar vida a partir dela.', 'Item', 100, 'Golem', 5, NULL),
    ('Design de Golem I', 'Essas imagens e anotações escritas às pressas parecem se assemelhar a um esquema de algum tipo. Algo parecido com o Golem que perambula pela Masmorra do Golem.', 'Book', 1500, 'Golem', 5, NULL),
    ('Design de Golem II', 'Assim como nós viemos da terra, a pedra também veio. Aproveitando a energia vital que flui pelo solo, animamos a pedra para nos servir.', 'Book', 2500, 'Golem', 1, NULL),
    ('Design de Golem III', 'Finalmente, imagens sobre a inserção de uma fonte de energia em um Golem. O mais frustrante, porém, é que a parte sobre a fusão da fonte de energia está riscada...', 'Book', 1500, 'Golem', 5, NULL),
    ('História do Golem I', 'Todos nós viemos da sujeira. A própria vida é sujeira. Um ciclo de nascimento e decadência. Algo de que nenhum homem, mulher ou mesmo pedra pode escapar.', 'Book', 2500, 'Golem', 1, NULL),
    ('História do Golem II', 'Assim como nós viemos da terra, a pedra também veio. Aproveitando a energia vital que flui pelo solo, animamos a pedra para nos servir.', 'Book', 2500, 'Golem', 1, NULL),
    ('História do Golem III', 'A pedra se ergueu para nos ajudar, para nos proteger. Enquanto nossas mãos criavam a vida deles, as mãos deles embalavam a nossa.', 'Book', 2500, 'Golem', 1, NULL),
    ('Cristal de Energia do Rei Golem', 'Um cristal enorme com energia suficiente para alimentar o enorme Rei Golem...', 'Item', 2500, 'Golem', 5, NULL),
    ('Anotações do Rei Golem', 'O rei da pedra. Imbuída do maior cristal de energia encontrado, essa entidade servirá para nos proteger de qualquer pessoa que nos queira mal.', 'Book', 2500, 'Golem', 5, NULL),
    ('Livro sobre Golem', 'O texto está muito desgastado, muito desbotado para ser legível. Mas os entalhes na capa de pedra são meticulosamente detalhados.', 'Item', 400, 'Golem', 5, NULL),
    -- ITENS DO TIPO POÇÃO:
    ('Poção do Deserto de Orientação', 'Os vaga-lumes guiarão o usuário até o próximo andar da Masmorra do Deserto.', 'Pocao', 8000, 'Mercador', 5, NULL);


    -- ITENS DO TIPO ARMA:

    -- ITENS DO TIPO ARMADURA:

    -- EFEITOS:
    INSERT INTO "efeito"
    ("nome", "descricao", "tipo", "valor", "duracaoTurnos")
    VALUES
    ('Envenenado', 'Dano contínuo ao longo do tempo', 3, 'debuff', 5),
    ('Queimado', 'Dano contínuo + interrupção de ações', 5, 'debuff', 4),
    ('Congelado', 'Impede movimento e ações', NULL, 'debuff', 2),
    ('Atordoado', 'Paralisa o alvo temporariamente', NULL, 'debuff', 1),
    ('Proteção', 'Escudo que absorve dano', 20, 'buff', 3),
    ('Cobiçado', 'Aumenta valor de venda do item', NULL, 'economia', NULL),
    ('Amaldiçoado', 'Dano se item estiver no inventário', 8, 'maldição', NULL),
    ('Maldição da Bolsa', 'Bloqueia uso do inventário', NULL, 'debuff', 3),
    ('Cura Pequena', 'Restaura 35 pontos de vida', 35, 'cura', 0),
    ('Cura Média', 'Restaura 70 pontos de vida', 70, 'cura', 0),
    ('Cura Grande', 'Restaura 150 pontos de vida', 150, 'cura', 0);

    -- DROPS DE MONSTROS

    -- LOJAS DE NPC